# -*- coding: UTF-8 -*-
#
# Copyright (c) 2014 darknao
# https://github.com/darknao/py02g
#
# This file is part of pyO2g.
# 
# pyO2g is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#----------------------------------------------------------------------
# This file was generated by img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

Icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAABIAAAASABGyWs+AAAACXZwQWcAAAAgAAAAIACH+pydAAAIEElEQVRYw82Xe2ze"
    "ZRXHP+d3ee/v23Zbd+lKl7GLA+YYQ26yOZRx2RBCIhJEUGSQCAG8JFMwmIgRhMw/CGLAKMZL"
    "RAGTgYwoBpjAGKzAxghsgqVdu7Zru7Zv+15/t+d5/KO/aQddGV4ST/LkTc5zfs/3+/ue85zz"
    "e+H/2W59et3XN27PD95xsHDa/wrDOdrGT165zjph1uobtzM023a6vwl8YfL+midytojM01rS"
    "kpAg25A79Oez+2r/NQK4ifNPalm3uL+4l90jD1x2xbNNtw0OZ5t8vM+Tqp0r6ehkSeiEYxtE"
    "wNO+XvdSc1fabdjW3DDn966d3PbTxc+Zf5vA3IbjN1Z1kWZ7BWNjTQ66sX35/EWzump7pGxV"
    "SeTATVtkk4aUCyLGrvqlxePjpcXvdg99pa156Y4bOs791gOLn905HQF7KuddL1/c/LE5ax4I"
    "JXACPLHtmcxIzc/uHHlaSmERywUrBU4CMkkh5QquLSCCh+BFkdXbM7AgKNcvu+TOVdVX7u1u"
    "/0gKuG7mKstxkwN+txSjYYrRIC8c2ko18NHa4GjBNmAUVD1NFBocC0IFYQhag52CvsGhxqBe"
    "uuumv52evn9Z++apsKypnLnUzGsGwy6GTRe9ag9v1J/ESgakshZu0kIAExmMpwmqUCrByJih"
    "WDJEdYOlIeEI6YLNaCXIv713363XtJ94yVRY8n7Hpm0rz1q28MIXPbtkV6Sfd4PtlD2PalXw"
    "qhAGBqM0tqMRMUbAGGPQGIwgGEQpiHwI6kJYg8gYs2ROfl8hnz3zt2sPlKdNgZvMXlPUB6Ws"
    "BzhoduNrj0hBFGr8OgR1g9HaLGhsG2sptD6WsTN7wLieqp46WOu/qLfS3agjLSpAIk8T1UFb"
    "QuBVB6tE1Wlr4IY/tRZM0v7cgNchY3ThSYVQgwoBI9gOWLbNqbNPf3xeYc7G21c8Upz8/IMd"
    "txSK3ugtr/S8tOlApTcvBkHELFqQO0TgXfX4Z0t6WgK1yJxvrPGGMBzTNVMSjRGlEZRgCdgO"
    "tDmtRMk31O0rxorvP+yri+8rAT/48b6bHt6befvXL7y7/ZOzZtg65fpXb9lQ7//QIgzsuW+O"
    "Dro/GzuU7PEr2cBESWVpV4kSbSJjdKTJNGgaGtSl176UOe5oV+vmE+7vXDLzhE+vXnTW93Ku"
    "df2W82p/OVqsTOW8/KkzbLH0KcryLtBubUPklE+JjO96vhJH5a1TF1pycKh49y8/Vbtt8nPX"
    "PnXuF3PZGV1Zu/DaD9c8FHAMNmUfePSinQp4LV53XvrU8nlC/QLL1DbUjL+uVG5pTCWqFfhX"
    "61/yXfdCz3T+ZkPblcZoU7tnV9Or/bWuF6tBZYdGvfqLzzwzeswKTGfrty5JLprZsrqQrm+7"
    "a2X7P4vq9PvclWesTb5eYLW1btbNxnIMYisGgm7dWdzn9Yzv31esjG63tLvDoHc+fOGOnmMm"
    "cP2zK5ctnHnyO99Z+atph8uNu7NbsvbsS3PRepY2LUccheWGxnYVjq2Mr8qmc7xTdRzofO7n"
    "a3euh6N0wsl2yZPpb5c82YvtbH2o+7b508Uaf9b3Pd821ahCX7WHvlo3fbVu6avvlz6/yypb"
    "A1brzJTTnOetaWvgsF21o2nFeMm947zFl0s6Y63vrrzz1r0dN9yTTWQfvL7tR2OTY+9+a6OU"
    "6uNnPvPe81HAFjeRsCnkssxubGJOw2yy6QRJE4mLUpX68OMfWgOX/3WhbSXUzhnRqlWLmpdK"
    "Kh+RTEZmzCuZscp4yVfVrUqZl+uhV7Rxj6/6tSt2979xkh9EopXBSQuprJBOW2SzQnN+Jg3p"
    "nNGlsCcY9Rc9dE6fmlKBlk2Im3Cs0M9cF/isbG3IyMHafiwdkctHEiUOyqFcR8OYV7uyVOfK"
    "kImpqDCSaUKsuhCEE8nVQKgMng/D1giBqRjGnT8+es6ImjIFLZsQIBsGUeHvbx54Z9kqeveP"
    "p9oyWVd05FGqHyCdK5NJi6QTRsSCWgKicGL4GA1hABJAWDNENYNKWujUxPS0tDZ2JdoyGfOI"
    "D5L82aSBOcD8etW3Tah6U03jn+gbqaSHo17xVB0vmrgICUdw7IkMBgaUnvgO0BFEvqBD0AoM"
    "BrHAtsVYgTuofb7x3u98/QECLZtIALOAFqARSJXG9bCtdO/cNmf54LCXEdeIZQuRFoIIIgVK"
    "GQIFUTSRCgtBDBgB4wiFTJaQEMexDYH9yHMXl56Y/NIWQON6BEgCeSDBRPoMYPX2RHs6Xi/d"
    "sXTOrPYU+VB7gqUmpC6VDeMlCCuAB/hABGIgKkuvPSC71rQ1k9A5vAqmNqqOkP+IW9CyiRTQ"
    "AGQBN16JeLmA0zwve2KhNbfWLpgzPF2eLxJZloAxE0dFVemvHNK7a0N6e1BRu9wEicuuzv+h"
    "Uj4u2f5290Cxs/7xoK5L/ZsJP0Bg7tcQK4HEqtgxcAPQNEkVBQRAcUZLwbVcmv26nwtr2g49"
    "lVSRzsWxxPHRaauTXzp+wdyLX32+/mRn79BdQDcw1L8ZfdQ+0PxlxJ1NHmiNayI9IS5BLHQA"
    "hDEhK95vBmYDmdgngCRTkpvbap81OmDtKleCdmA30Ne/man7AICeGHIqBqvGcZlYETs+3BwG"
    "iffd+FfFZDXg+J6pdXdEzwNjwBBQPAx+VAIjj2FaNlEDDgAjcV1kYxKpSXVhT3pbMwn8sELJ"
    "WJU8MBCfd8Tft2OahnGDsmLCTgzsTAInJqBjAoeJOHEN5YAKMNy/Ge8jE/hPLCYvAIcLb7L9"
    "AwfE4+0ewaOHAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDEwLTAyLTExVDAxOjA5OjQxLTA2OjAw"
    "149ILAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAwNy0xMC0xNlQyMzo1MTo0OC0wNTowMNDNlqsA"
    "AAAASUVORK5CYII=")
index.append('Icon')
catalog['Icon'] = Icon
getIconData = Icon.GetData
getIconImage = Icon.GetImage
getIconBitmap = Icon.GetBitmap
getIconIcon = Icon.GetIcon

